---
# TODO Add pi-hole DNS entry
# TODO Add caddy entry

- name: Setup Proxmox node
  hosts: proxmox_nodes
  tasks:
    - name: "Setup services in {{ inventory_hostname }}"
      loop: "{{ groups[inventory_hostname + '_containers'] }}"
      include_role:
        name: setup_service
      vars:
        service: "{{ item }}"
